const Map<String, String> en = {"log_in":"Log in",
"sign_up":"Sign up", "log_to_sign": "Don't have an account yet? Sign up",
 "Log_in":"Log in", "enter_password":"Enter password:", "enter_email":"Enter email:",
 "registered_successfully":"User registered successfully","login_successfull":"User logged in successfully",
 "fields":"Please fill in all the fields", "credentials": "Wrong credentials", "settings":"Settings", "PL_switch": "Switch to polish",
  "EN_switch": "Switch to english", "save":"Save", "my_profile": "My profile", "play_game": "Play game", "change_avatar": "Change avatar",
  "sign_to_log":"Already have an account? Sign in", "enter_username":"Enter username:", "email_format":"Wrong format of email", 
  "short_password": "Password is too short", "uppercase":"Password must contain at least one uppercase letter", 
  "numerical": "Password must contain at least one number", "repeat_password": "Repeat password:", "password_match":"Passwords do not match",
};