const Map<String, String> en = {
  "log_in": "Log in",
  "sign_up": "Sign up",
  "log_to_sign": "Don't have an account yet? Sign up",
  "Log_in": "Log in",
  "enter_password": "Enter password:",
  "enter_new_password": "Enter new password:",
  "enter_new_email": "Enter new email:",
  "enter_new_username": "Enter new username:",
  "enter_email": "Enter email:",
  "registered_successfully": "User registered successfully",
  "continue": "continue",
  "username_found":"Username already exists",
  "login_successfull": "User logged in successfully",
  "fields": "Please fill in all the fields",
  "credentials": "Wrong credentials",
  "settings": "Settings",
  "PL_switch": "Switch to polish",
  "EN_switch": "Switch to english",
  "first_mode": "Mode 1:",
  "second_mode": "Mode 2:",
  "save": "Save",
  "message2":"Remember to click Save button at the end of the game to save the results of the game",
  "choose":"Choose",
  "choose_avatar":"Choose your avatar",
  "my_profile": "My profile",
  "play_game": "Play game",
  "change_avatar": "Change avatar",
  "sign_to_log": "Already have an account? Sign in",
  "enter_username": "Enter username:",
  "email_format": "Wrong format of email",
  "short_password": "Password is too short",
  "uppercase": "Password needs at least one uppercase letter",
  "numerical": "Password must contain at least one number",
  "repeat_password": "Repeat password:",
  "password_match": "Passwords do not match",
  "choose_theme": "Choose theme:",
  "choose_mode": "Choose mode:",
  "mode1": "Click on the screen only when given symbol is displayed",
  "mode2": "Click on the screen only when given symbol is NOT displayed",
  "yes": "yes",
  "no": "no",
  "your_result": "Your result",
  "start_game": "Are you ready to start the game?",
  "tapped": "Tapped",
  "not_tapped": "Not tapped",
  "instructionMode1":
      "React by clicking on the screen only when this symbol is displayed",
  "instructionMode2":
      "React by clicking on the screen only when this symbol is NOT displayed",
  "message": "Click on the screen to begin the game",
  "delete": "Delete account",
  "account_deletion": "Account deletion",
  "delete_info": "Are you sure you want to delete the account?",
  "log_out": "Log out",
  "update": "Edit profile",
  "end_message": "You finished the game! Do you want to repeat the task?",
  "email_repeat": "User with this email address already exists",
  "unknown_error": "Unknown error",
  "played_games": "Played games",
  "congrats": "Congrats!",
  "notification":
      "You've finished 6 games of one of the available modes. Your result is now being analized by your Doctor. Keep up the good work!",
  "result_message":
      "Here we keep track of all the games you've completed. Every sixth game the results will be send to your doctor for analysis"
};
