const Map<String, String> en = {
  "log_in": "Log in",
  "sign_up": "Sign up",
  "log_to_sign": "Don't have an account yet? Sign up",
  "Log_in": "Log in",
  "enter_password": "Enter password:", "enter_new_password": "Enter new password:",
  "enter_email": "Enter email:",
  "registered_successfully": "User registered successfully",
  "login_successfull": "User logged in successfully",
  "fields": "Please fill in all the fields",
  "credentials": "Wrong credentials",
  "settings": "Settings",
  "PL_switch": "Switch to polish",
  "EN_switch": "Switch to english",
  "save": "Save",
  "my_profile": "My profile",
  "play_game": "Play game",
  "change_avatar": "Change avatar",
  "sign_to_log": "Already have an account? Sign in",
  "enter_username": "Enter username:",
  "email_format": "Wrong format of email",
  "short_password": "Password is too short",
  "uppercase": "Password must contain at least one uppercase letter",
  "numerical": "Password must contain at least one number",
  "repeat_password": "Repeat password:",
  "password_match": "Passwords do not match",
  "choose_theme": "Choose theme:",
  "choose_mode": "Choose mode:",
  "mode1": "Click on the screen only when given symbol is displayed",
  "mode2": "Click on the screen only when given symbol is NOT displayed",
  "yes": "yes",
  "no": "no",
  "start_game": "Are you ready to start the game?",
  "instructionMode1":
      "React by clicking on the screen only when this symbol is displayed",
  "instructionMode2":
      "React by clicking on the screen only when this symbol is NOT displayed",
  "message": "Click on the screen to begin the game","delete":"delete account", "account_deletion": "Account deletion",
  "delete_info":"Are you sure you want to delete the account?", "log_out":"Log out", "update":"edit profile",
};
