const Map<String, String> pl = {
  "log_in": "Logowanie",
  "sign_up": "Rejestracja",
  "log_to_sign": "Nie masz jeszcze konta? Zarejestruj się",
  "Log_in": "Zaloguj",
  "enter_password": "Wpisz hasło:",
  "enter_new_password": "Wpisz nowe hasło:",
  "enter_new_email": "Wpisz nowy email:",
  "enter_new_username": "Wpisz nową nazwę użytkownika:",
  "enter_email": "Wpisz email:",
  "registered_successfully": "Poprawnie zarejestrowano",
  "login_successfull": "Poprawnie zalogowano",
  "fields": "Proszę wypełnić wszystkie pola",
  "credentials": "Wprowadzono złe dane",
  "settings": "Ustawienia",
  "PL_switch": "Zmień na polski",
  "EN_switch": "Zmień na angielski",
  "save": "Zapisz",
  "my_profile": "Mój profil",
  "play_game": "Graj",
  "change_avatar": "Ustaw awatar",
  "sign_to_log": "Masz już konto? Zaloguj się",
  "enter_username": "Wpisz nazwę użytkownika:",
  "email_format": "Zły format adresu mailowego",
  "short_password": "Hasło jest za krótkie",
  "uppercase": "Hasło musi zawierać conajmniej jedną wielką literę",
  "numerical": "Hasło musi zawierać conajmniej jedną cyfrę",
  "choose_mode": "Wybierz tryb:",
  "repeat_password": "Powtórz hasło:",
  "password_match": "Hasła są różne",
  "choose_theme": "Wybierz motyw",
  "mode1": "Kliknij na ekran tylko wtedy, gdy wyświetlony jest dany symbol",
  "mode2": "Kliknij na ekran tylko wtedy, gdy dany symbol NIE jest wyświetlany",
  "yes": "tak",
  "continue": "kontynuuj",
  "no": "nie",
  "start_game": "Czy chcesz zacząć grę?",
  "instructionMode1":
      "Reaguj klikając na ekran tylko wtedy, gdy wyświetli się ten symbol",
  "instructionMode2":
      "Reaguj klikając na ekran tylko wtedy, gdy ten symbol NIE jest wyświetlany",
  "message": "Kliknij na ekran, aby rozpocząć grę",
  "delete": "Usuń konto",
  "account_deletion": "Usunięcie konta",
  "delete_info": "Czy na pewno chcesz usunąć konto?",
  "log_out": "Wyloguj się",
  "update": "Edytuj profil",
  "end_message": "Gra zakończona! Czy chcesz powtórzyć?",
  "email_repeat": "Użytkownik o danym adresie mailowym już istnieje",
  "unknown_error": "Nieznany error",
  "your_result": "Twój wynik",
  "tapped": "Kliknięto",
  "not_tapped": "Nie kliknięto",
  "first_mode": "Tryb 1:",
  "second_mode": "Tryb 2:",
  "played_games": "Zakończone gry",
  "congrats": "Gratulacje!",
  "notification":
      "Ukończono 6 gier w jednym z dostępnych trybów. Twój wynik jest teraz analizowany przez Twojego lekarza. Tak trzymaj!",
  "result_message":
      "Tutaj widoczne są wszystkie ukończone przez Ciebie gry. Co szóstą grę wyniki zostaną wysłane do Twojego lekarza w celu analizy"
};
